### ISSUE TITLE
Add a "random strategy" that plays on a randomly picked column

### ISSUE THREAD

**Issue by apojomovsky** [apojomovsky/cuatro_en_linea#29]

**Comment by apojomovsky** [comment]
FYI @basicNew

**Comment by basicNew** [comment]
Sorry, I think I wasn't clear when we talked today. By random strategy I mean a strategy that picks which column to play at random (of course choosing from the available non-full columns).

**Comment by apojomovsky** [comment]
Oh! I totally misunderstood what you wanted to tell me, thanks for the clarification.
