### ISSUE TITLE
Add a `prepare` call to the strategies

### ISSUE THREAD

**Issue by basicNew** [apojomovsky/cuatro_en_linea#33]
Allow strategies to "prepare" before starting the match:

- Implement an empty method (`pass`) in the superclass. 
- Receive the color of the player. 
- Call it in the match, just before starting the loop to play.

**Comment by basicNew** [comment]
This is addressed in https://github.com/apojomovsky/cuatro_en_linea/pull/55. Close when it is merged

**Comment by apojomovsky** [comment]
Fixed in #55
