### ISSUE TITLE
Define hardware and function for baseline comparison

### ISSUE THREAD

**Issue by basicNew** [apojomovsky/cuatro_en_linea#36]
- Define the hardware that will be used.
- Define a function (and add the code of it to the repo) so that users can tests the equivalent on their machine. Should be something along the lines of:
``` 
import time

def fib(n):
    if n == 0: return 0
    elif n == 1: return 1
    else: return fib(n-1) + fib(n-2)

start_time = time.time()
fib(20)
end_time = time.time()
print("Evaluation took %s seconds" % (end_time - start_time))
```

- Find in the hardware the equivalent function of 25 msecs (for each play) and 5 secs (for the prepare)

**Comment by apojomovsky** [comment]
These are the closest values I was able to get on my server (8 cores Xeon Nehalem @3Ghz)
```
Evaluation of number 24 took 0.0222659111023 seconds
Evaluation of number 35 took 4.47464179993 seconds
```
While on my laptop (2 cores i5 Westmere @2.66Ghz), the closest numbers I get are:
```
Evaluation of number 24 took 0.0252530574799 seconds
Evaluation of number 35 took 5.00039792061 seconds
```
There's no much difference between them because they share almost the same microarchitecture and similar frequency. That made me think about the following: Should we care about the multithreaded algorithms? Since it seems it'd be pretty easy to fool our reference system by making use of them. What do you think @basicNew ?

**Comment by basicNew** [comment]
First of all, numbers form my old rusty machine:

```
Evaluation of 24 took 0.0347290039062 seconds
Evaluation of 35 took 6.67835402489 second
```

So I guess it does makes sense to have a baseline computation :).

About multithreading: Great observation! I actually have been thinking about that too. And actually it would make a lot of sense to give time for a strategy to keep doing things while the other strategy is computing. What I have so far is:

- the `multithreading` package provides the ability to spawn processes with a similar API of threads. 
- it also provides the concept of a pool, so e.g. if you create a pool of 4 workers then you can use 4 cores.
- We could create a pool of 3 cores for each strategy and give it to them in the "prepare" phase. The strategy can do as he wants with that, from completely ignoring it to start computing on those three cores. So each strategy would get 3 cores and the main program the remaining 2 (assuming we have the 8 cores available for us).

Having said that, I would really give this idea low priority in comparison to the rest of the things. Let's keep it in the back of our heads.
